config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  get 'charts/index' => 'charts#index'

 get 'categories' =>'category#index'
    get 'categories' =>'category#index'
    get 'categories/new' =>"category#new"
    post 'categories' =>"category#create"
    delete 'categories/:id/' =>'category#destroy' ,as: :delete_categories
    resources :category
    resources :users, only: [:new, :create]
    resources :incomes
    delete 'incomes/:id/' =>'incomes#destroy' ,as: :delete_incomes
    # resources :reports


    resources :costs
    delete 'costs/:id/' =>'costs#destroy' ,as: :delete_costs

	get 'home/profile'

	get 'login' => 'sessions#new'
  	post 'login' => 'sessions#login_user'
 
	get '/auth/:provider/callback' => 'sessions#create'
	get 'auth/failure', to: redirect('/')
	delete 'signout', to: 'sessions#destroy', as: 'signout'


    get 'chart', to: 'application#charts'

end

app/models/category.rb
class Category < ApplicationRecord
belongs_to :user
	has_many :income_categories 
	has_many :incomes ,through: :income_categories

	has_many :cost_categories
	has_many :costs, through: :cost_categories
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
   before_action :authenticate_user!
	def new
		@category=Category.new
	end

	def index
	
		@category=current_user.categories.all
	end

	def create
		
		@category=current_user.categories.new(category_params)
		if @category.save
			redirect_to categories_path
		else
			render :new
		end
	end

	def edit
		@category=current_user.categories.find(params[:id])
	
	end

	def destroy
		@category=current_user.categories.find(params[:id])
		@category.destroy
		redirect_to :back
	end

	def update
		@category=current_user.categories.find(params[:id])
		@update_category=@category.update(category_params)
		redirect_to  categories_path
	end
	private
		def category_params
			params.require(:category).permit(:name)
		end
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/views/category/edit.html.erb
	<body>
		<div class="col-sm-4" style="margin-left: 427px;margin-top: 50px">
			<div class="rcol-md-offset-3">
				<div class="main-login main-center">
				<h1>UpDate Category</h1>
					<%= form_for @category do |f|  %>	

						 <div class="form-group">
       						 <%= f.text_field :name, class: 'form-control'%>
      					</div>
					
						<div class="form-group ">
						<%= f.submit "Save", class: "btn btn-primary btn-lg btn-block login-button" %>

						</div>
						
			
					<% end %>
				</div>
			</div>
		</div>

		 <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
	</body>

app/views/category/index.html.erb
<div class="container">
  <h1>Categories</h1>
       
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Created at</th>
        <th>Actions</th>
      </tr>
    </thead>
    <% @category.each do |category| %>
    <tbody>
      <tr>
        <td><%= category.id %></td>
        <td><%= category.name %></td>
        <td><%= category.created_at %></td>
        <td>
          <%= link_to "Edit", edit_category_path(category), method: :get, 
            class: "btn btn-info" %>
          <%= link_to "Delete", delete_categories_path(category), method: :delete, data:{confirm: 'Are you sure?'}, class: "btn btn-warning" %>
        </td>
      </tr>
    </tbody>
    <% end %>
  </table>

  <%= link_to "New Categorie", categories_new_path , class: "btn btn-info"%>
</div>

app/views/category/new.html.erb
	<body>
		<div class="col-sm-4" style="margin-left: 427px;margin-top: 50px">
			<div class="rcol-md-offset-3">
				<div class="main-login main-center">
				<h1>New Category</h1>
					<%= form_for @category do |f|  %>	

						 <div class="form-group">
        					<%= f.text_field :name, class: 'form-control', placeholder: 'New category' %>
      					</div>
					
						<div class="form-group ">
						<%= f.submit "Save", class: "btn btn-primary btn-lg btn-block login-button" %>

						</div>
						
			
					<% end %>
				</div>
			</div>
		</div>

		 <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
	</body>