config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  get 'charts/index' => 'charts#index'

 get 'categories' =>'category#index'
    get 'categories' =>'category#index'
    get 'categories/new' =>"category#new"
    post 'categories' =>"category#create"
    delete 'categories/:id/' =>'category#destroy' ,as: :delete_categories
    resources :category
    resources :users, only: [:new, :create]
    resources :incomes
    delete 'incomes/:id/' =>'incomes#destroy' ,as: :delete_incomes
    # resources :reports


    resources :costs
    delete 'costs/:id/' =>'costs#destroy' ,as: :delete_costs

	get 'home/profile'

	get 'login' => 'sessions#new'
  	post 'login' => 'sessions#login_user'
 
	get '/auth/:provider/callback' => 'sessions#create'
	get 'auth/failure', to: redirect('/')
	delete 'signout', to: 'sessions#destroy', as: 'signout'


    get 'chart', to: 'application#charts'

end

app/models/cost.rb
class Cost < ApplicationRecord
belongs_to :user
	has_many :cost_categories
	has_many :categories ,through: :cost_categories
end

app/controllers/costs_controller.rb
class CostsController < ApplicationController
  before_action :authenticate_user!
  def index
  	@costs=current_user.costs
  end

  def new

  	@categories=current_user.categories
  	@cost = current_user.costs.new
  end

  def create

  	@cost = current_user.costs.new(cost_params)
  	if @cost.save
      redirect_to costs_path
    else
      render :new
    end
  end

  def edit
    @categories=current_user.categories
    @cost =current_user.costs.find params[:id]
  end

  def update
    @cost =current_user.costs.find params[:id]
    @cost_update=@cost.update(cost_params)
    redirect_to costs_path
  end

  def destroy
    @cost = current_user.costs.find params[:id]
    @cost.destroy
    redirect_to :back
  end
  private
  def cost_params
  	params.require(:cost).permit :amount , category_ids: []


  end
end

app/helpers/costs_helper.rb
module CostsHelper
	def first_day_of_month
	 cost_chart = current_user.costs
	 start_month = cost_chart.minimum(:created_at)
	 
	end

	def last_day_of_month
		cost_chart = current_user.costs
		end_month = cost_chart.maximum(:created_at)
	end

	def total_costs 
	arr= []
     cost_chart=current_user.costs
	 arr.push(cost_chart.where("?<= created_at AND created_at<=?",first_day_of_month,last_day_of_month).sum(:amount))
	 return arr
	end

	def each_category_costs
		
	end
end

app/views/costs/edit.html.erb
<%#= method_name %>
	<body>
		<div class="col-sm-4" style="margin-left: 427px;margin-top: 50px">
			<div class="rcol-md-offset-3">
				<div class="main-login main-center">
				<h1>Edit Incomes</h1>
					<%= form_for @cost do |f|  %>	
						 <div class="form-group">
        					 <%= f.label :amount, "Amount" %> 
        					<%= f.text_field :amount, class: 'form-control'%>
      					</div>
						<label>Categories</label>

						<!-- <div class="checkbox">
  							<label><input type="checkbox" value="">Option 1</label>
						</div> -->

						<br><%= f.collection_check_boxes :category_ids, @categories, :id, :name %></br>

						
						<div class="form-group ">

						<%= f.submit "Save", class: "btn btn-primary btn-lg btn-block login-button" %>

						</div>
						
			
					<% end %>
				</div>
			</div>
		</div>

		 <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
	</body>

app/views/costs/index.html.erb
<div class="container">
  <h1>Costs</h1>
       
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Id</th>
        <th>Amount</th>
        <th>Categories</th>
        <th>Created at</th>
        <th>Actions</th>
      </tr>
    </thead>
    <% @costs.each do |cost| %>
    <tbody>
      <tr>
        <td><%= cost.id %></td>
        <td><%= cost.amount %></td>
        <td>
          <% a=cost.categories %>
          <% a.each do |t| %>
           <%= t.name %>,
          <% end %>
        </td>
        <td><%= cost.created_at %></td>
        <td>
          <%= link_to "Edit", edit_cost_path(cost), method: :get, 
            class: "btn btn-info" %>
          <%= link_to "Delete", delete_costs_path(cost), method: :delete, data:{confirm: 'Are you sure?'}, class: "btn btn-warning" %>
        </td>
      </tr>
    </tbody>
    <% end %>
  </table>

  <%= link_to "New Cost", new_cost_path , class: "btn btn-info"%>
</div>

app/views/costs/new.html.erb
<%#= method_name %>
	<body>
		<div class="col-sm-4" style="margin-left: 427px;margin-top: 50px">
			<div class="rcol-md-offset-3">
				<div class="main-login main-center">
				<h1>New cost</h1>
					<%= form_for @cost do |f|  %>	
						 <div class="form-group">
        					 <%= f.label :amount, "Amount" %> 
        					<%= f.text_field :amount, class: 'form-control'%>
      					</div>
						<label>Categories</label>

						<!-- <div class="checkbox">
  							<label><input type="checkbox" value="">Option 1</label>
						</div> -->

						<br><%= f.collection_check_boxes :category_ids, @categories, :id, :name %></br>

						
						<div class="form-group ">

						<%= f.submit "Save", class: "btn btn-primary btn-lg btn-block login-button" %>

						</div>
						
			
					<% end %>
				</div>
			</div>
		</div>

		 <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
	</body>