config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  get 'charts/index' => 'charts#index'

 get 'categories' =>'category#index'
    get 'categories' =>'category#index'
    get 'categories/new' =>"category#new"
    post 'categories' =>"category#create"
    delete 'categories/:id/' =>'category#destroy' ,as: :delete_categories
    resources :category
    resources :users, only: [:new, :create]
    resources :incomes
    delete 'incomes/:id/' =>'incomes#destroy' ,as: :delete_incomes
    # resources :reports


    resources :costs
    delete 'costs/:id/' =>'costs#destroy' ,as: :delete_costs

	get 'home/profile'

	get 'login' => 'sessions#new'
  	post 'login' => 'sessions#login_user'
 
	get '/auth/:provider/callback' => 'sessions#create'
	get 'auth/failure', to: redirect('/')
	delete 'signout', to: 'sessions#destroy', as: 'signout'


    get 'chart', to: 'application#charts'

end

app/models/income.rb
class Income < ApplicationRecord
	belongs_to :user
	has_many :income_categories
	has_many :categories, through: :income_categories
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
    before_action :authenticate_user!
  def index
  
    @incomes=current_user.incomes
    # @categories=@incomes.cate
  end

  def new
  
     @categories = current_user.categories
     @income = current_user.incomes.new
  end

  def edit
    @categories =current_user.categories
    @income = current_user.incomes.find params[:id]
  end

  def update
    @income = current_user.incomes.find params[:id]

    @update_income = @income.update(income_params)
    redirect_to incomes_path

  end

  def create
    # @categories = current_user.categories
    
    @income = current_user.incomes.new(income_params)

    if @income.save
      redirect_to incomes_path
    else
      render :new
    end
  end

  def destroy
    @income =Income.find params[:id]
    @income.destroy
    respond_to do |format|
      format.html { redirect_to incomes_path }
      format.json { head :no_content }
      format.js   { render :layout => false }
   end
  end
  private
  def income_params
    params.require(:income).permit :amount, category_ids: []
  end
end

app/helpers/incomes_helper.rb
require 'date'
module IncomesHelper
	def income_first_day_of_month
	 income_chart = current_user.incomes
	 income_chart.minimum(:created_at)
	 
	end

	def income_last_day_of_month
		income_chart = current_user.incomes
		income_chart.maximum(:created_at)

	end

	def total_incomes
		arr= []
     	income_chart=current_user.incomes
		
		first_day_of_month= income_chart.minimum(:created_at)
		last_day_of_month= income_chart.maximum(:created_at)
	 	
	 	arr.push(income_chart.where("?<= created_at AND created_at<=?",income_first_day_of_month, income_last_day_of_month).sum(:amount))
	 	
	 	return arr

		# return []
	end
end
 # Income.where("? < created_at AND created_at < ?", 1, 30).sum(:amount)
#   c.created_at.where("?< created_at.day AND created_at.day<?",1,30)
# c.select("amount").where("?< created_at AND created_at<?",1,30)
# > d=User.find(2).costs

app/views/incomes/destroy.js.erb
$('#delete_income').html("<%= j (render @income) %>");

app/views/incomes/edit.html.erb
<%#= method_name %>
	<body>
		<div class="col-sm-4" style="margin-left: 427px;margin-top: 50px">
			<div class="rcol-md-offset-3">
				<div class="main-login main-center">
				<h1>Edit Incomes</h1>
					<%= form_for @income do |f|  %>	
						 <div class="form-group">
        					 <%= f.label :amount, "Amount" %> 
        					<%= f.text_field :amount, class: 'form-control'%>
      					</div>
						<label>Categories</label>

						<!-- <div class="checkbox">
  							<label><input type="checkbox" value="">Option 1</label>
						</div> -->

						<br><%= f.collection_check_boxes :category_ids, @categories, :id, :name %></br>

						
						<div class="form-group ">

						<%= f.submit "Save", class: "btn btn-primary btn-lg btn-block login-button" %>

						</div>
						
			
					<% end %>
				</div>
			</div>
		</div>

		 <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
	</body>

app/views/incomes/index.html.erb
<div class="container">
  <h1>Incomes</h1>
       
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Id</th>
        <th>Amount</th>
        <th>Categories</th>
        <th>Created at</th>
        <th>Actions</th>
      </tr>
    </thead>
    <% @incomes.each do |cost| %>
    <tbody>
      <tr>
        <td><%= cost.id %></td>
        <td><%= cost.amount %></td>
        <td>
          <% a=cost.categories %>
          <% a.each do |t| %>
           <%= t.name %>,
          <% end %>
        </td>
        <td><%= cost.created_at %></td>
        <td>
          <%= link_to "Edit", edit_income_path(cost), method: :get, 
            class: "btn btn-info" %>
          <%= link_to "Delete", delete_incomes_path(cost), method: :delete, data:{confirm: 'Are you sure?'}, :id => 'delete_income', class: "btn btn-warning" %>
        </td>
      </tr>
    </tbody>
    <% end %>
  </table>

  <%= link_to "New Cost", new_income_path , class: "btn btn-info"%>
</div>

app/views/incomes/new.html.erb
<%#= method_name %>
	<body>
		<div class="col-sm-4" style="margin-left: 427px;margin-top: 50px">
			<div class="rcol-md-offset-3">
				<div class="main-login main-center">
				<h1>New Incomes</h1>
					<%= form_for @income do |f|  %>	
						 <div class="form-group">
        					 <%= f.label :amount, "Amount" %> 
        					<%= f.text_field :amount, class: 'form-control'%>
      					</div>
						<label>Categories</label>

						<!-- <div class="checkbox">
  							<label><input type="checkbox" value="">Option 1</label>
						</div> -->

						<br><%= f.collection_check_boxes :category_ids, @categories, :id, :name %></br>

						
						<div class="form-group ">

						<%= f.submit "Save", class: "btn btn-primary btn-lg btn-block login-button" %>

						</div>
						
			
					<% end %>
				</div>
			</div>
		</div>

		 <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
	</body>