config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  get 'charts/index' => 'charts#index'

 get 'categories' =>'category#index'
    get 'categories' =>'category#index'
    get 'categories/new' =>"category#new"
    post 'categories' =>"category#create"
    delete 'categories/:id/' =>'category#destroy' ,as: :delete_categories
    resources :category
    resources :users, only: [:new, :create]
    resources :incomes
    delete 'incomes/:id/' =>'incomes#destroy' ,as: :delete_incomes
    # resources :reports


    resources :costs
    delete 'costs/:id/' =>'costs#destroy' ,as: :delete_costs

	get 'home/profile'

	get 'login' => 'sessions#new'
  	post 'login' => 'sessions#login_user'
 
	get '/auth/:provider/callback' => 'sessions#create'
	get 'auth/failure', to: redirect('/')
	delete 'signout', to: 'sessions#destroy', as: 'signout'


    get 'chart', to: 'application#charts'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
belongs_to :user
	has_many :income_categories 
	has_many :incomes ,through: :income_categories

	has_many :cost_categories
	has_many :costs, through: :cost_categories
end

app/models/cost.rb
class Cost < ApplicationRecord
belongs_to :user
	has_many :cost_categories
	has_many :categories ,through: :cost_categories
end

app/models/cost_category.rb
class CostCategory < ApplicationRecord
	belongs_to :cost
	belongs_to :category
end

app/models/income.rb
class Income < ApplicationRecord
	belongs_to :user
	has_many :income_categories
	has_many :categories, through: :income_categories
end

app/models/income_category.rb
class IncomeCategory < ApplicationRecord
	belongs_to :income
	belongs_to :category
	# validates :category_id, allow_nil: true , presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :categories
  has_many :incomes
  has_many :costs
  def self.sign_in_from_omniauth(auth)
    find_by(provider: auth['provider'], uid: auth['uid']) ||
            create_user_from_omniauth(auth)
  end

  def self.create_user_from_omniauth(auth)
    create(
      provider: auth['provider'],
      uid: auth['uid'],
      name: auth['info']['name'],
      password: "12341234"
    )
  end
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  include IncomesHelper
  include CostsHelper
  before_action :authenticate_user!
  def index
    cost_chart = current_user.costs
    # start_month = cost_chart.minimum(:created_at).month
    # end_month = cost_chart.maximum(:created_at).month
    arr= []
    cost_chart.each{|k| arr.push(k.created_at)}
    @chart = LazyHighCharts::HighChart.new('graph') do |f|
      f.title(:text => "Total costs And Incomes Col")
      f.xAxis(:categories => arr )
      
      f.series(:name => "Costs", :yAxis => 0, :data => total_costs)
      f.series(:name => "Incomes", :yAxis => 1, :data => total_incomes)
      # byebug
      f.yAxis [
        {:title => {:text => "Costs", :margin => 70} },
        {:title => {:text => "Incomes"}, :opposite => true},
      ]

      f.legend(:align => 'right', :verticalAlign => 'top', :y => 75, :x => -50, :layout => 'vertical',)
      f.chart({:defaultSeriesType=>"column"})
    end
    #########  income
    @chart5 = LazyHighCharts::HighChart.new('pie') do |f|
          f.chart({:defaultSeriesType=>"pie" , :margin=> [50, 200, 60, 170]} )
          series = {
                   :type=> 'pie',
                   :name=> 'Total',
                   :data=> [
                      ['Costs',   total_costs[0]],
                      ['Incomes', total_incomes[0]],
                   ]
          }
          f.series(series)
          f.options[:title][:text] = "Total costs And Incomes Pie"
          f.legend(:layout=> 'vertical',:style=> {:left=> 'auto', :bottom=> 'auto',:right=> '50px',:top=> '100px'}) 
          f.plot_options(:pie=>{
            :allowPointSelect=>true, 
            :cursor=>"pointer" , 
            :dataLabels=>{
              :enabled=>true,
              :color=>"black",
              :style=>{
                :font=>"13px Trebuchet MS, Verdana, sans-serif"
              }
            }
          })
    end
end
end

app/controllers/costs_controller.rb
class CostsController < ApplicationController
  before_action :authenticate_user!
  def index
  	@costs=current_user.costs
  end

  def new

  	@categories=current_user.categories
  	@cost = current_user.costs.new
  end

  def create

  	@cost = current_user.costs.new(cost_params)
  	if @cost.save
      redirect_to costs_path
    else
      render :new
    end
  end

  def edit
    @categories=current_user.categories
    @cost =current_user.costs.find params[:id]
  end

  def update
    @cost =current_user.costs.find params[:id]
    @cost_update=@cost.update(cost_params)
    redirect_to costs_path
  end

  def destroy
    @cost = current_user.costs.find params[:id]
    @cost.destroy
    redirect_to :back
  end
  private
  def cost_params
  	params.require(:cost).permit :amount , category_ids: []


  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_auth

  def index
  end

  def set_auth
    @auth = session[:omniauth] if session[:omniauth]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  	@users =User.new
    @kt = false
  end
  def create
  	@user = User.create(users_params)
  	if @user.save
  		redirect_to '/'
  	else 
  		render :new
  	end
  end

  private 
  	def users_params
  		params.require(:user).permit(:name, :email ,:password , :password_confirmation)
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/costs_helper.rb
module CostsHelper
	def first_day_of_month
	 cost_chart = current_user.costs
	 start_month = cost_chart.minimum(:created_at)
	 
	end

	def last_day_of_month
		cost_chart = current_user.costs
		end_month = cost_chart.maximum(:created_at)
	end

	def total_costs 
	arr= []
     cost_chart=current_user.costs
	 arr.push(cost_chart.where("?<= created_at AND created_at<=?",first_day_of_month,last_day_of_month).sum(:amount))
	 return arr
	end

	def each_category_costs
		
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/incomes_helper.rb
require 'date'
module IncomesHelper
	def income_first_day_of_month
	 income_chart = current_user.incomes
	 income_chart.minimum(:created_at)
	 
	end

	def income_last_day_of_month
		income_chart = current_user.incomes
		income_chart.maximum(:created_at)

	end

	def total_incomes
		arr= []
     	income_chart=current_user.incomes
		
		first_day_of_month= income_chart.minimum(:created_at)
		last_day_of_month= income_chart.maximum(:created_at)
	 	
	 	arr.push(income_chart.where("?<= created_at AND created_at<=?",income_first_day_of_month, income_last_day_of_month).sum(:amount))
	 	
	 	return arr

		# return []
	end
end
 # Income.where("? < created_at AND created_at < ?", 1, 30).sum(:amount)
#   c.created_at.where("?< created_at.day AND created_at.day<?",1,30)
# c.select("amount").where("?< created_at AND created_at<?",1,30)
# > d=User.find(2).costs

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/time_helper.rb
module TimeHelper
	def add_data_isue
		a=current_user.costs.fir
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<!-- // -->
<div class="container" style="margin-top: 350px">

    <hr>
        <div class="text-center center-block">
            <p class="txt-railway">- TDT -</p>
            <br />
                <a href="https://www.facebook.com/bootsnipp"><i id="social-fb" class="fa fa-facebook-square fa-3x social"></i></a>
              <a href="https://twitter.com/bootsnipp"><i id="social-tw" class="fa fa-twitter-square fa-3x social"></i></a>
              <a href="https://plus.google.com/+Bootsnipp-page"><i id="social-gp" class="fa fa-google-plus-square fa-3x social"></i></a>
              <a href="mailto:bootsnipp@gmail.com"><i id="social-em" class="fa fa-envelope-square fa-3x social"></i></a>
</div>
    <hr>
</div>

app/views/layouts/_header.html.erb
 <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <span class="navbar-brand"> Money Lover</span>
    </div>
    <ul class="nav navbar-nav ">
      <li class="active"><%= link_to "Home", charts_index_path %></li>
      <li class="dropdown ">
        <% if current_user %>
        <a class="dropdown-toggle-right" data-toggle="dropdown" href="#"><%= current_user.name %>
        <span class="caret"></span></a>
        <% else %>
        <a class="dropdown-toggle-right" data-toggle="dropdown" href="#">Login
        <span class="caret"></span></a>
          <% end %>
        <ul class="dropdown-menu">
        <% if current_user %>
          <li><%= link_to "Categories", categories_path %></li>
          <li><%= link_to "Incomes", incomes_path %></li>
          <li><%= link_to "Costs", costs_path %></li>
          <li><%= link_to "Setting", '#' %></li>
          <li><%= link_to "Statistical", charts_index_path %></li>
          <li><%= link_to "Logout", signout_path , method: :delete %></li>

         <% else %>
          <li><%= link_to "Login", login_path%></li>
          <% end %>

        </ul>
      </li>
      <% if session[:omniauth] %>
      
      <% end %>
      
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MoneyLover</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">
  </head>

  <body>
 
  <%= render "layouts/header" %>
    <%= yield %>
    <% if @kt != false %>
    <%= render "layouts/footer" %>
   <% end %>
  </body>
</html>